name: Create/Release Package

on:
  push:
    branches:
      - main

jobs:

  # build / test
  Build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - uses: actions/checkout@v2

      # Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install Dependencies
      - run: npm ci

      # Build Package
      - run: npm run build

      # Run Tests
      - run: npm test

  # create / release
  Release:
    needs: Build
    name: Create Release Package
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - uses: actions/checkout@v2

      # Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # Show current package
      - name: cat package.json
        run: cat ./package.json

      # Install Dependencies
      - run: npm ci

      # Update Changelog
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'

      # Create Release
      - name: Create New Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to NPM
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}


