name: Create Package

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Package Release
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Show current package
      - name: cat package.json
        run: cat ./package.json

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Generate CHANGLOG.md with pre-commit hook
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Bump package version
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Export tag parameter
      - name: Export TAG Parameter
        id: tag_name
        run: |
          echo ::set-output name=TAG::`cat package.json | jq -r .version`
        shell: bash

      # Create New Release
      - name: Create New Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ steps.tag_name.outputs.TAG }}
            release_name: Release ${{ steps.tag_name.outputs.TAG }}
            body: ''
            draft: false
            prerelease: false